---

#===========================================================================
# Delete VM
#===========================================================================
- name: Power off VM - {{ vmware_hostname }}
  community.vmware.vmware_guest:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: '{{ vcenter_verify_ssl }}'
    datacenter: "{{  vcenter_datacenter }}"
    datastore: "{{  vcenter_datastore }}"
    cluster: "{{  vcenter_cluster }}"
    name: "{{ vcenter_cluster }}-{{ vmware_hostname }}"
    folder: "{{ vmware_folder }}"
    state: powered-off
  tags:
    - vmware_destroy_vm

- name: Destroy VM - {{ vmware_hostname }}
  community.vmware.vmware_guest:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: '{{ vcenter_verify_ssl }}'
    datacenter: "{{  vcenter_datacenter }}"
    datastore: "{{  vcenter_datastore }}"
    cluster: "{{  vcenter_cluster }}"
    name: "{{ vcenter_cluster }}-{{ vmware_hostname }}"
    folder: "{{ vmware_folder }}"
    state: absent
  tags:
    - vmware_destroy_vm

#===========================================================================
# Delete ISO
#===========================================================================

- name: Check for the ISO
  community.vmware.vsphere_file:
    host: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: '{{ vcenter_verify_ssl }}'
    datacenter: "{{ vmware_datacenter }}"
    datastore: "{{ {{ vmware_datastore }} }}"
    path: "{{ iso_path_loc }}"
    state: file
  ignore_errors: true
  register: vmware_check_for_iso
  tags:
    - vmware_destroy_vm
    - vmware_check_for_iso

- name: Delete the iso if present
  when: vmware_check_for_iso.state != "absent"
  community.vmware.vsphere_file:
    host: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: '{{ vcenter_verify_ssl }}'
    datacenter: "{{ vmware_datacenter }}"
    datastore: "{{ {{ vmware_datastore }} }}"
    path: "{{ iso_path_loc }}"
    state: absent
  ignore_errors: true
  tags:
    - vmware_destroy_vm
    - vmware_delete_iso

#===========================================================================
# vCenter Organizational Structure
#===========================================================================

- name: Delete Cluster Folder
  community.vmware.vcenter_folder:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: '{{ vcenter_verify_ssl }}'
    datacenter_name: "{{ vcenter_datacenter }}"
    folder_name: "{{ vmware_folder }}"
    folder_type: vm
    state: absent
  ignore_errors: true
  tags:
    - vmware_destroy_vm
    - vmware_delete_folder